version: '3.5'

services:
  postgres_service:
    container_name: postgres_sql
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
      POSTGRES_DB: archive
    volumes:
       - postgres:/data/postgres
       - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - 5432
    restart: always
    networks:
      - mina_network

  pgadmin_service:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_PORT}
    volumes:
       - pgadmin:/root/.pgadmin
    expose:
      - ${PGADMIN_PORT}
    restart: always
    depends_on:
      - postgres_service
    networks:
      - mina_network

  mina_archive:
    container_name: mina_archive
    image: "minaprotocol/mina-archive:1.1.3-48401e9"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    entrypoint: "coda-archive"
    command: "run -postgres-uri postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres_sql:5432/archive -server-port ${ARCHIVE_PORT}"
    restart: always
    expose:
      - ${ARCHIVE_PORT}
    depends_on:
      - postgres_service
    networks:
      - mina_network
  
  nginx_service:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
       - pgadmin_service
    ports:
      - "1585:1585"
      - "5050:5050"
    networks:
      - mina_network

networks:
  mina_network:
    name: mina_network
    driver: bridge

volumes:
    postgres:
    pgadmin:
    database_data:


